#!/usr/bin/env php
<?php

namespace Behavioral\Command;

require_once 'vendor/autoload.php';

$registry = new Registry(new Lamp());

$registry->setCommand(new TurnOnCommand(), new CommandType('on'));
$registry->setCommand(new TurnOffCommand(), new CommandType('off'));
$registry->setCommand(new ToggleCommand(), new CommandType('toggle'));

$registry->execute(new CommandType('on'));
$registry->execute(new CommandType('off'));
$registry->execute(new CommandType('toggle'));
$registry->execute(new CommandType('toggle'));
