#!/usr/bin/env php
<?php

namespace Behavioral\Command;

require_once 'vendor/autoload.php';

$registry = new Registry(new Lamp());

try {
    $registry->setCommand('on', new TurnOnCommand());
    $registry->setCommand('off', new TurnOffCommand());
    $registry->setCommand('toggle', new ToggleCommand());
    $registry->execute('on');
    $registry->execute('off');
    $registry->execute('toggle');
    $registry->execute('toggle');
} catch (\Exception $e) {
    printf('%s', 'Caught exception: ' . $e->getMessage() . "\n");
}
